### ISSUE TITLE
QA_174_Report

### ISSUE THREAD

**Issue by monika30peatix** [monika30peatix/TestRepo#16]
# QA Status: PASS

## Test details
- Dev Instance https://54-248-205-27.peatix.dev/
- Android Chrome, IOS Safari, PC Chrome, PC Safari
- Iphone SE, iOS 16.2 (Safari)
- Android Aquos sense3 Version:11 (Chrome)
- MacOS Monterey 12.6 Version: 108.0.5359.124 (Chrome)
- MacOS Monterey 12.6 Version 15.6.1 17613.3.9.1.16 (Safari)
- Refer  [Test doc](https://docs.google.com/spreadsheets/d/1qhHBLCc8gPRmUImGa5lgDH6aCxgYqdYUeTNkKrJw2l8/edit?usp=sharing)
 
### AC
- [x] **AC#1** - new Subscriptions upon page load or refresh is unchanged. This means it should work/look the way it does today(before the change)
- [x] **AC#2** - Creating new subscription after editing and cancelling pre-existing subscription acts the same as new subscription on page refresh
- [x] **AC#3** - All error handling remains the same as prior to deployment
"All the error handling during subscription creation does not have an error message. When the required field is not entered, the field is highlighted in red."

### Steps & Observed:

 1. From the Group page, start creating a new subscription and reload the page while creating a new subscription 
2. On the 'Create a Plan', Reload the page using the reload button/Reload address bar
     - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

 3. Proceed to the 'Create a Plan' page again and click the 'Continue' button without entering any information
     - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

 4. Fill out the fields of 'Create a Plan' page and Click the 'Continue' button 
     - **Observed**: Successfully move onto the next page 🟢 PASS

5. On the 'Subscription form' page create a form with a few features and Reload the page using the reload button/Reload address bar
    - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

6. Proceed to the 'Subscription form' page again and Click the 'Continue' button without entering any information
      - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

7. Create a form on the 'Subscription form' page and click the 'Continue' button 
      - **Observed**: Successfully move onto the next page 🟢 PASS

8. Proceed to the 'Terms of Services' page enter some info and Reload the page using the reload button/Reload address bar
      - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

9. Proceed to the 'Terms of Services form' page again and click the 'Save as Draft' button without entering any information
      - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

10. Fill out the fields of 'Terms of Services' page and click the 'Save as draft' button 
     - **Observed**: Successfully move onto the next page 🟢 PASS

11. Steps to check for **AC#2** behavior
      a. Go to the Groups page
      b. Click on Subscriptions -> Plans
      c. Edit existing subscription with pencil button(or follow common steps to create a new one)
      d. Click the cancel button at the bottom
      e. Click on the Create New subscription Button
      - **Observed**: A new subscription creation page is displayed (any previous field data is cleared) 🟢 PASS
   

## Screenshots/Recordings

<details>
<summary> Join live chat button display </summary>

 - PC Chrome - More than 30 min before the event start time
   
![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668083-74e43c21-7148-4e93-a1f6-ea9ae07a3e5a.png)

 - PC Chrome  - At 30 min before the event start time

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668216-d12adf95-384b-46b7-98d7-73eb2e6e59d2.png)

 - IOS Safari - More than 30 min before the event start time

![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668136-88f9bb4d-8897-47d4-9e8e-9517f8dc6118.jpeg)

 - IOS Safari - At 30 min before the event start time

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668251-302b9023-2cee-4eb8-bb35-aa7b4166316f.jpeg)

</details>

<details>
<summary>Text-only message is successfully sent </summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668460-00b82837-33b2-4b1d-827b-b00cc395d66c.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668525-ee7eb142-2c54-4b07-9445-3742f16f0a8c.mp4
 
</details>

<details>
<summary>Emoji-only message is successfully sent</summary>

- PC Chrome

-  IOS Safari

 
</details>

<details>
<summary></summary>

- PC Chrome

-  IOS Safari

 
</details>

<details>
<summary></summary>

- PC Chrome

-  IOS Safari

 
</details>
 
<details>
 
<summary></summary>

- PC Chrome

-  IOS Safari

 </details>

<details>
 
<summary></summary>

- PC Chrome

-  IOS Safari

 </details>

<details>
<summary></summary>
 
- PC Chrome

-  IOS Safari

 </details>

<details>
 
<summary> </summary>

- PC Chrome

-  IOS Safari

 </details>

<details>

<summary> </summary>

- PC Chrome

-  IOS Safari

</details>

<details>
 
<summary></summary>

- PC Chrome

-  IOS Safari

</details>

<details>
 
<summary></summary>

- PC Chrome

-  IOS Safari

 </details>

<details>
 
<summary></summary>

 </details>

<details>
<summary> </summary>

 - PC Chrome 

- IOS Safari

</details>

<details>
<summary></summary>

 - PC Chrome 

 - IOS Safari

</details>
