### ISSUE TITLE
QA_183

### ISSUE THREAD

**Issue by monika30peatix** [monika30peatix/TestRepo#17]
# QA Status: PASS

## Test details
- RestoreTest  https://restoretest.peatix.com/
- PC Chrome
- MacOS Monterey 12.6 Version: 108.0.5359.124 (Chrome)
- Refer  [Test doc](https://docs.google.com/spreadsheets/d/1D1cEwyY-3t1H5Wuupiw7wvVN1ka2mWdKkxfd0qBUKus/edit#gid=769598148)
 
### AC
- [x] **AC#1** - new Subscriptions upon page load or refresh is unchanged. This means it should work/look the way it does today(before the change)
- [x] **AC#2** - Creating new subscription after editing and cancelling pre-existing subscription acts the same as new subscription on page refresh
- [x] **AC#3** - All error handling remains the same as prior to deployment
"All the error handling during subscription creation does not have an error message. When the required field is not entered, the field is highlighted in red."

### Steps & Observed:

1. Steps to check for **AC#1** behavior
   a. From the Group page, start creating a new subscription and reload the page while creating a new subscription 
   b. On the '**Create a Plan**'/ '**Subscription form**'/ '**Terms of Services**' pages, enter some info and reload the 
       page using the reload button/Reload address bar
   - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

2.  Steps to check for **AC#2** behavior
      a. Go to the Groups page
      b. Click on Subscriptions -> Plans
      c. Edit existing subscription with pencil button(or follow common steps to create a new one)
      d. Click the cancel button at the bottom
      e. Click on the Create New subscription Button
      - **Observed**: A new subscription creation page is displayed (any previous field data is cleared) 🟢 PASS

 3. Steps to check for **AC#3** behavior
     a. Proceed to the '**Create a Plan**'/ '**Subscription form**'/ '**Terms of Services**'  pages again and click the 
         'Continue' button for each pages without entering any information
      - **Observed**: All mandatory fields are highlighted in red 🟢 PASS
      
     b. Fill out the fields of '**Create a Plan**'/ '**Subscription form**'/ '**Terms of Services**'  pages and click the 
         'Continue' button 
     - **Observed**: Successfully move onto the next page 🟢 PASS

 
## Screenshots/Recordings

<details>
<summary> AC#1 new Subscriptions upon page load or refresh is unchanged</summary>

 - Create A Plan Page

https://user-images.githubusercontent.com/109570108/214514621-5a31390c-6681-4c3d-b127-6816c0dd32ed.mov

https://user-images.githubusercontent.com/109570108/214514686-3948dc8c-cf3f-485e-8d43-eb09f30292b1.mov

- Subscription form

https://user-images.githubusercontent.com/109570108/214514768-c6e4c283-b90d-4d9b-93a3-91c44c8157f2.mov

https://user-images.githubusercontent.com/109570108/214514819-8b4956ff-110d-40af-a1cb-32a95af39d30.mov

-  Terms of Services

https://user-images.githubusercontent.com/109570108/214514884-4779129a-218c-4717-84a2-eaf7da0e0a83.mov

https://user-images.githubusercontent.com/109570108/214514912-796380d8-53f6-4c8e-bab0-efb444129532.mov

</details>

<details>
<summary>AC#2 Creating new subscription after editing and cancelling pre-existing subscription acts the same as new subscription on page refresh </summary>

https://user-images.githubusercontent.com/109570108/214515389-49913827-73ce-43a8-9771-e7f326002976.mov

</details>

<details>
<summary>AC#3 All error handling remains the same as prior to deployment </summary>

- Create a Plan

https://user-images.githubusercontent.com/109570108/214516822-599963ef-dcc9-470d-9cc1-d6b6d7968a92.mov

https://user-images.githubusercontent.com/109570108/214516843-ec581d5f-74da-4ff2-81cc-8d877f90d789.mov

- Subscription form

https://user-images.githubusercontent.com/109570108/214516983-4626951f-61b3-4c92-96a8-f55d54216874.mov

https://user-images.githubusercontent.com/109570108/214517005-cca5079c-2ad9-49b5-9887-06bf2f354680.mov

- Terms of Services

https://user-images.githubusercontent.com/109570108/214517138-1eb9bcf6-97aa-47fc-883e-97eb3129b9bd.mov

https://user-images.githubusercontent.com/109570108/214517198-922245a1-cf30-4fa9-b3bc-a955aea72a00.mov

</details>
