### ISSUE TITLE
QA_191_Report

### ISSUE THREAD

**Issue by monika30peatix** [monika30peatix/TestRepo#19]
# QA Status: PASS

## Test details
- Tested on Restoretest
- Android Aquos sense3 Version:11, Build: Peatix Beta 3.2.26 (1037)
- Refer  [Test doc](https://docs.google.com/spreadsheets/d/13NYk4fHJEJyPhwxSoPe7EqbLGmqtOw_Xn69HF5VAwJ8/edit?usp=sharing)
 
## AC
- [x]  **AC#1:** Upon changing their payment method to Stripe, a paid invoice amounting to 0 and an upcoming invoice on the original expiration date should exist in the Stripe subscription dashboard. The Stripe subscription is in a trial period. (Similar to [AC#1 of original issue](https://github.com/Peatix/peatix/issues/7851)).
- [x]  **AC#2:** Upon changing their payment method to Stripe, the membership/subscription, should be ACTIVE and PAID respectively.  (Similar to [AC#2 of original issue](https://github.com/Peatix/peatix/issues/7851))
- [x]  **AC#3:** There should be no subscription payout record created.
- [x]  **AC#4:** After renewal with Stripe, the membership and subscription statuses should transition from PENDING_RENEWAL and PENDING_RENEWAL to  ACTIVE and PAID respectively after the invoice is finalized (Similar to [AC#3,AC#4,AC#5 of original issue](https://github.com/Peatix/peatix/issues/7851)).
- [x]  **AC#5:** Once the subscription is renewed, there should be a subscription payout record created.

### Pre-Steps to check the behavior in PC Chrome / Mobile Safari:
 1. As organizer A, create a JP group
 2. As organizer A, create a subscription plan for the group - **Plan A** i.e. `3-Day Exact Days Plan A 1000 JPY`
 3. Exact Day Plan = 3 days
 4. no initial fee
 5. recurring fee = 1000 JPY
 
### Pre-Steps to check the behavior in PC Safari / Android Chrome:
 1. As organizer B, create a JP group
 2. As organizer B, create a subscription plan for the group - **Plan B** i.e. `3-Day Exact 
      Days Plan B 1000 JPY Int Fee 3000 JPY`
 3.  Exact Day Plan = 3 days
 4.  Initial fee = 3000 JPY
 5.  recurring fee = 1000 JPY

### Steps:
 Steps to check for **AC#1: Upon changing their payment method to Stripe, a paid invoice amounting to 0 and an upcoming invoice on the original expiration date should exist in the Stripe subscription dashboard. The Stripe subscription is in a trial period** behavior -
   1. Sign in to another user account 
   2. Order subscription for **3-Day Exact Days Plan A 1000 JPY** via Combini via PC Chrome / Mobile Safari & **3-Day 
         Exact Days Plan B 1000 JPY Int Fee 3000 JPY** via Combini via PC Safari / Android Chrome
   3. As subscriber, complete the Combini payment via QA setup 
   4. As Peatix Staff, confirm the subscription sale is ACTIVE and PAID in stafftools
   5. As subscriber, sign in to own account and accesses the renewal URL 
   6. Complete the switching from Combini to Stripe
   7. As Peatix Staff, locate the Stripe_customer_id in the subscriber's Stafftools > User Details page
   8. Look up the customer ID in Stripe Dashboard - JPY
   9. Accesses the Stripe customer record and subscription record

       - **Observed**: 
             - Customer has a subscription sale record 🟢 PASS
             - Stripe subscription shows that it is in trial period 🟢 PASS
             - The trial period reflects the remaining period of the current subscription cycle before the expiration 
                date 🟢 PASS
             - This Stripe subscription (trial) has a paid invoice amounting to 0 🟢 PASS
             - There's also another upcoming invoice that reflects the recurring fee 🟢 PASS

 Steps to check for **AC#2: Upon changing their payment method to Stripe, the membership/subscription, should be ACTIVE and PAID respectively** behavior -

10. As Peatix Staff, confirm the subscription sale in stafftools
      
      - **Observed**:  
            - Membership status = ACTIVE 🟢 PASS
            - Subscription status = PAID 🟢 PASS

 Steps to check for **AC#3: There should be no subscription payout record created.** behavior -

11. As Peatix staff, go to Stafftools > Groups > Payout
12. Look up the payout with Subscription Plan ID and payout status (PREPARED)
      
      - **Observed**: 
            - Confirm no payout record is created for initial fee and recurring fee for this subscription sale 🟢 PASS

Steps to check for **AC#4: After renewal with Stripe, the membership and subscription statuses should transition from PENDING_RENEWAL and PENDING_RENEWAL to ACTIVE and PAID respectively after the invoice is finalized.** behavior -

13. Wait for 3 days to finish the remaining cycle of the subscription paid via Combini
14. As Peatix staff, go to Stripe Dashboard - JPY
15. Accesses the Stripe customer record
      
      - **Observed**:  
            - Stripe subscription shows that the trial period has finished 🟢 PASS
            - The invoice that reflects the recurring fee is finalizing within 1 hour 🟢 PASS
            
16. As Peatix Staff, confirm the subscription sale in stafftools within this hour

      - **Observed**:  
            - Membership status = PENDING_RENEWAL 🟢 PASS
            - Subscription status = PENDING_RENEWAL 🟢 PASS

17. Wait for ~ one hour (may take a few more minutes)
18. As Peatix staff, go to Stripe Dashboard - JPY
19. Confirm the invoice is finalized 
20. As Peatix Staff, go to the subscription sale in stafftools

      - **Observed**:  
            - Membership status = ACTIVE 🟢 PASS
            - Subscription status = PAID 🟢 PASS

Steps to check for **AC#5: Once the subscription is renewed, there should be a subscription payout record created.** behavior -

21. As Peatix staff, go to Stafftools > Groups > Payout
22. Look up the payout with Subscription Plan ID and payout status (PREPARED)
      
      - **Observed**:  
            - Confirm payout record is created for this subscription sale 🟢 PASS

 
## Screenshots/Recordings

<details>
<summary> AC#1: Upon changing their payment method to Stripe, a paid invoice amounting to 0 and an upcoming invoice on the original expiration date should exist in the Stripe subscription dashboard. The Stripe subscription is in a trial period</summary>

 - PC Chrome

https://user-images.githubusercontent.com/109570108/226831251-e6ffbe5d-a183-4ecb-a80f-f2b4aced52a2.mov

- IOS Safari

https://user-images.githubusercontent.com/109570108/226831949-8181999d-02a7-4074-b009-013160ad2ebf.MP4

- PC Safari

https://user-images.githubusercontent.com/109570108/226832245-e590e1fa-278d-4271-b3a5-e397b7c8a135.mov

</details>

<details>
<summary>AC#2: Upon changing their payment method to Stripe, the membership/subscription, should be ACTIVE and PAID respectively.</summary>

 - PC Chrome
 
https://user-images.githubusercontent.com/109570108/226835311-bae5de41-8c6d-429a-93cb-da20de443d4e.mov

- IOS Safari

https://user-images.githubusercontent.com/109570108/226835466-bf64a5f9-d5fe-4f28-bfa4-bc7b09a20839.mov

- Android Chrome

https://user-images.githubusercontent.com/109570108/226835580-412d6d10-dc02-4774-b25c-0ec679e1d862.mov

</details>

<details>
<summary>AC#3: There should be no subscription payout record created.</summary>

- PC Chrome (one payout record for Subs 813 created on 17-03-2023)

https://user-images.githubusercontent.com/109570108/227150838-f738513d-f569-4bc8-a35c-82e5a75d2da3.mov

- PC Safari (one payout record for Subs 814 created on 17-03-2023)

https://user-images.githubusercontent.com/109570108/227151083-046352f0-b785-42fc-a9b6-12d8114e4b86.mov

- IOS Safari (one payout record for Subs 815 created on 17-03-2023)

https://user-images.githubusercontent.com/109570108/227151179-1d96ca1a-89b5-472d-a2a4-6854fabb0e33.mov

</details>

<details>
<summary>AC#4: After renewal with Stripe, the membership and subscription statuses should transition from PENDING_RENEWAL and PENDING_RENEWAL to ACTIVE and PAID respectively after the invoice is finalized.</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/226837396-e36be658-3dd3-4307-b2d9-f1a2074bb7c5.mov

- Membership status = PENDING_RENEWAL - Subscription status = PENDING_RENEWAL
https://user-images.githubusercontent.com/109570108/226837476-f4ad41ef-fea9-4e71-b476-58a5dc4322aa.mov

- Membership status = ACTIVE - Subscription status = PAID
https://user-images.githubusercontent.com/109570108/226837507-dc7f50b3-87b2-4898-9f9e-243e8a02ddc9.mov

- PC Safari

https://user-images.githubusercontent.com/109570108/226837660-2c84a9cb-bd70-4554-a031-7a70b0822e98.mov

- Membership status = PENDING_RENEWAL - Subscription status = PENDING_RENEWAL
https://user-images.githubusercontent.com/109570108/226837701-33858dcb-5e9d-4595-ba87-1045dc2185c6.mov

- Membership status = ACTIVE - Subscription status = PAID
https://user-images.githubusercontent.com/109570108/226837739-46df3d1c-33b9-4b0f-abf0-60a384eb05da.mov

- Android Chrome

https://user-images.githubusercontent.com/109570108/226838494-d50442cb-235d-4dec-b0ad-4149a79b8d7d.mov

- Membership status = PENDING_RENEWAL - Subscription status = PENDING_RENEWAL
https://user-images.githubusercontent.com/109570108/226838558-ff1b181d-ceff-478a-9544-7f7271c5a376.mov

- Membership status = ACTIVE - Subscription status = PAID
https://user-images.githubusercontent.com/109570108/226838594-576f3122-3130-48e5-8849-fe21cfbf29d7.mov

</details>

<details>
<summary>AC#5: Once the subscription is renewed, there should be a subscription payout record created.</summary>

- Final Payout Record

![QA_183_A007_screenshot](https://user-images.githubusercontent.com/109570108/227151353-6b199fcc-b4a9-45dd-ade0-81c25beb36e6.png)

- PC Chrome  (Two payout records for Subs 813 created on 20-03-2023)

https://user-images.githubusercontent.com/109570108/226839275-3addc5a0-2c64-4c17-bf9d-955b84a5f713.mov

- PC Safari (Two payout records for Subs 814 created on 20-03-2023)

https://user-images.githubusercontent.com/109570108/226839394-f19e75ba-b3ca-4e76-babf-14a067a6a1a3.mov

- IOS Safari  (Two payout records for Subs 815 created on 20-03-2023)

https://user-images.githubusercontent.com/109570108/226839583-38a724f4-8b1d-4372-a5f9-df8d1bd7a656.mov

</details>
