### ISSUE TITLE
Test QA Report

### ISSUE THREAD

**Issue by monika30peatix** [monika30peatix/TestRepo#5]
# AC#2 - Live Chat: PASS
Assignee: @monika30peatix 

## Test details
- Dev Instance https://35-78-200-110.peatix.dev/
- PC Chrome, IOS Safari
- MacOS Monterey 12.6 Version: 108.0.5359.124 (Chrome)
- Iphone SE, iOS 16.2 (Safari)
- Refer  [Test doc](https://docs.google.com/spreadsheets/d/1TcY0tkrrkJ1Y7VJqQS1adx3LsUWwdtpI8_WgM0otvGU/edit#gid=22960666)
 
### AC
- [x] **AC#2.0** - Display "Join live chat" button 30 minutes before the event starts.
- [x] **AC#2.1** - Users should be able to send messages containing text and emojis.
- [x] **AC#2.2** - When users delete their own message, it will be replaced by _"Message deleted"_.
- [x] **AC#2.3** -  `Organizers` can block users
	- Popup appears asking the organizer to confirm if this is the intended action.
- [x] **AC#2.4** - `Organizers` and `attendees` should be able to hide the live chat.

### Pre-steps

Refer [Test Pre Steps](https://docs.google.com/spreadsheets/d/1TcY0tkrrkJ1Y7VJqQS1adx3LsUWwdtpI8_WgM0otvGU/edit#gid=769598148&range=F31)
 
### Steps
Refer [Test Steps](https://docs.google.com/spreadsheets/d/1TcY0tkrrkJ1Y7VJqQS1adx3LsUWwdtpI8_WgM0otvGU/edit#gid=769598148&range=G31)

 
### Observed
Below Results are on the basis of [Test Case ID](https://docs.google.com/spreadsheets/d/1TcY0tkrrkJ1Y7VJqQS1adx3LsUWwdtpI8_WgM0otvGU/edit#gid=769598148&range=A31:D31)

<details>
<summary> QA_141_B001 🟢</summary>

- PC Chrome

![PC Chrome](https://user-images.githubusercontent.com/109570108/213663952-72965e5d-431c-4484-b094-af8cdf7ed98f.png)

- IOS Safari

https://user-images.githubusercontent.com/109570108/213666543-e8e96eae-f212-49c9-b09a-87713bc6d676.mov

</details>
 
<details>
 
<summary> QA_141_B002 🟢</summary>

- PC Chrome

![QA_141_B002](https://user-images.githubusercontent.com/109570108/213667361-f6c166ec-f55d-4cbd-bf3e-071da7da4731.png)

-  IOS Safari
 

https://user-images.githubusercontent.com/109570108/213667422-9158f979-c41e-4a5b-99c9-c3d2b0addcc1.mp4

</details>

<details>
 
<summary> QA_141_B003 🟢</summary>

- PC Chrome

![QA_141_B003](https://user-images.githubusercontent.com/109570108/213667580-521beb64-745f-44c5-b3c1-a052b6c2bd77.png)

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213667611-b1b34889-2a74-4284-8061-22a9abcbfb75.mp4

 </details>

<details>
 
<summary> QA_141_B004 🟢</summary>

- PC Chrome

![QA_141_B004](https://user-images.githubusercontent.com/109570108/213667691-835be222-f6fc-4c53-81e1-174d06a65975.png)

-  IOS Safari

![QA_141_B004](https://user-images.githubusercontent.com/109570108/213667742-7cb21961-4b3b-4f5d-897a-e8313faa5963.jpeg)

 </details>

<details>
 
<summary> QA_141_B005 🟢</summary>

- PC Chrome

![QA_141_B005](https://user-images.githubusercontent.com/109570108/213667828-fad39b75-5034-4ef6-8750-92a8078659f1.png)

-  IOS Safari

![QA_141_B005](https://user-images.githubusercontent.com/109570108/213667893-1e4b38d9-bf2f-4e67-b630-05d5b382ad61.jpeg)

 </details>

<details>
 
<summary> QA_141_B006 🟢</summary>

- PC Chrome

![QA_141_B006](https://user-images.githubusercontent.com/109570108/213667960-eb6cc50d-8cfb-4bca-bca3-6afc6382bc1a.png)

-  IOS Safari
![QA_141_B006](https://user-images.githubusercontent.com/109570108/213668010-5a8356a6-5134-4e49-8c64-775207f0ba00.jpeg)

 </details>

<details>
 
<summary> QA_141_B007 🟢</summary>

- PC Chrome

![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668083-74e43c21-7148-4e93-a1f6-ea9ae07a3e5a.png)

-  IOS Safari

![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668136-88f9bb4d-8897-47d4-9e8e-9517f8dc6118.jpeg)

 </details>

<details>
 
<summary> QA_141_B008 🟢</summary>

- PC Chrome

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668216-d12adf95-384b-46b7-98d7-73eb2e6e59d2.png)

-  IOS Safari

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668251-302b9023-2cee-4eb8-bb35-aa7b4166316f.jpeg)

 </details>

<details>
 
<summary> QA_141_B009 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668460-00b82837-33b2-4b1d-827b-b00cc395d66c.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668525-ee7eb142-2c54-4b07-9445-3742f16f0a8c.mp4

 </details>

<details>
 
<summary> QA_141_B010 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668610-5497db3c-53f5-4241-8e99-7772d860da7c.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668662-d6f0401d-3c80-4e9c-b1b1-c6dc887153a6.mp4

 </details>

<details>
 
<summary> QA_141_B011 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668731-9d68911c-4d64-49f3-b927-6ddecf5a0287.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668832-9893c269-6eb5-4078-92b0-e50b3effaaa1.mp4

 </details>

<details>
 
<summary> QA_141_B012 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668910-94df1c7f-b704-4e1c-bfd3-47af41114d14.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668970-7cc9d0a3-102f-4edb-a68c-9ba841a45ff8.mp4

</details>

<details>
 
<summary> QA_141_B013 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669090-3d4f22bf-83d2-44a2-affd-8d3612dc45e5.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669129-3d7da8d1-273f-4326-a3f2-0552130d4ed6.mp4

 </details>

<details>
 
<summary> QA_141_B014 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669240-e83899e3-283b-45d9-858a-3be8e8178289.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669283-b2829583-f144-4105-92dd-0be20cbbd580.mp4

 </details>

<details>
 
<summary> QA_141_B015 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669361-539ac267-1033-4f2c-bad6-8ef3a36d4b0f.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669402-f44c8d94-0cc8-4fc0-9ece-1a9661f45e13.mp4

 </details>

<details>
 
<summary> QA_141_B016 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669472-d7f427e6-4c0d-454e-9c42-76fc8efcc2ab.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669541-21662cf0-64e3-46ba-9316-15e05adc9205.mp4

 </details>

<details>
 
<summary> QA_141_B017 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669658-c3dc802d-bc59-4ccd-ab0c-e7d491006ae8.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669727-1d1848c4-ff9d-49cb-a244-e414a84ac1ef.mp4

</details>

<details>
 
<summary> QA_141_B018 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669827-a5beb642-eb6e-4cac-a1bb-ffeaa62efddb.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669870-1ddaf8ce-af6e-4a42-9d98-b9f85892057a.mp4

</details>

<details>
 
<summary> QA_141_B019 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669958-3c536bd5-ee08-4211-8b18-65514da00d8d.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213670035-a89c22e9-037e-4198-97b3-45bb2187b7a8.mp4

 </details>

<details>
 
<summary> QA_141_B020 🟢</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213670135-ea715e52-ed4a-4d34-a35e-e9d1a4a98b2e.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213670234-ebb59987-68bc-494b-975f-373c6555af06.mp4

 </details>
