### ISSUE TITLE
QA_150_NEW_REPORT

### ISSUE THREAD

**Issue by monika30peatix** [monika30peatix/TestRepo#8]
# QA Status: PASS

## Test details
- Dev Instance  https://43-207-32-206.peatix.dev/
- PC Chrome
- MacOS Monterey 12.6 Version: 108.0.5359.124 (Chrome)
- Refer  [Test doc](https://docs.google.com/spreadsheets/d/1D1cEwyY-3t1H5Wuupiw7wvVN1ka2mWdKkxfd0qBUKus/edit#gid=769598148)
 
### AC
- [x] **AC#1** - new Subscriptions upon page load or refresh is unchanged. This means it should work/look the way it does today(before the change)
- [x] **AC#2** - Creating new subscription after editing and cancelling pre-existing subscription acts the same as new subscription on page refresh
- [x] **AC#3** - All error handling remains the same as prior to deployment
"All the error handling during subscription creation does not have an error message. When the required field is not entered, the field is highlighted in red."

### Steps & Observed:

 1. From the Group page, start creating a new subscription and reload the page while creating a new subscription 
2. On the 'Create a Plan'/ 'Subscription form'/ Reload the page using the reload button/Reload address bar
     - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

 3. Proceed to the 'Create a Plan' page again and click the 'Continue' button without entering any information
     - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

 4. Fill out the fields of 'Create a Plan' page and Click the 'Continue' button 
     - **Observed**: Successfully move onto the next page 🟢 PASS

5. On the 'Subscription form' page create a form with a few features and Reload the page using the reload button/Reload address bar
    - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

6. Proceed to the 'Subscription form' page again and Click the 'Continue' button without entering any information
      - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

7. Create a form on the 'Subscription form' page and click the 'Continue' button 
      - **Observed**: Successfully move onto the next page 🟢 PASS

8. Proceed to the 'Terms of Services' page enter some info and Reload the page using the reload button/Reload address bar
      - **Observed**: Directed back to the Create Subscription Plans page (https://peatix.com/group/{group_id}/membership_types) 🟢 PASS

9. Proceed to the 'Terms of Services form' page again and click the 'Save as Draft' button without entering any information
      - **Observed**: All mandatory fields are highlighted in red 🟢 PASS

10. Fill out the fields of 'Terms of Services' page and click the 'Save as draft' button 
     - **Observed**: Successfully move onto the next page 🟢 PASS

11. Steps to check for **AC#2** behavior
      a. Go to the Groups page
      b. Click on Subscriptions -> Plans
      c. Edit existing subscription with pencil button(or follow common steps to create a new one)
      d. Click the cancel button at the bottom
      e. Click on the Create New subscription Button
      - **Observed**: A new subscription creation page is displayed (any previous field data is cleared) 🟢 PASS
   

## Screenshots/Recordings

<details>
<summary> Join live chat button display </summary>

 - PC Chrome - More than 30 min before the event start time
   
![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668083-74e43c21-7148-4e93-a1f6-ea9ae07a3e5a.png)

 - PC Chrome  - At 30 min before the event start time

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668216-d12adf95-384b-46b7-98d7-73eb2e6e59d2.png)

 - IOS Safari - More than 30 min before the event start time

![QA_141_B007](https://user-images.githubusercontent.com/109570108/213668136-88f9bb4d-8897-47d4-9e8e-9517f8dc6118.jpeg)

 - IOS Safari - At 30 min before the event start time

![QA_141_B008](https://user-images.githubusercontent.com/109570108/213668251-302b9023-2cee-4eb8-bb35-aa7b4166316f.jpeg)

</details>

<details>
<summary>Text-only message is successfully sent </summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668460-00b82837-33b2-4b1d-827b-b00cc395d66c.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668525-ee7eb142-2c54-4b07-9445-3742f16f0a8c.mp4
 
</details>

<details>
<summary>Emoji-only message is successfully sent</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668610-5497db3c-53f5-4241-8e99-7772d860da7c.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668662-d6f0401d-3c80-4e9c-b1b1-c6dc887153a6.mp4
 
</details>

<details>
<summary>Text-and-emoji message is successfully sent</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668731-9d68911c-4d64-49f3-b927-6ddecf5a0287.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668832-9893c269-6eb5-4078-92b0-e50b3effaaa1.mp4
 
</details>

<details>
<summary>Text-only message is replaced by "Message deleted</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213668910-94df1c7f-b704-4e1c-bfd3-47af41114d14.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213668970-7cc9d0a3-102f-4edb-a68c-9ba841a45ff8.mp4
 
</details>
 
<details>
 
<summary>Emoji-only message is replaced by "Message deleted"</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669090-3d4f22bf-83d2-44a2-affd-8d3612dc45e5.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669129-3d7da8d1-273f-4326-a3f2-0552130d4ed6.mp4

 </details>

<details>
 
<summary>Text-and-emoji message is replaced by "Message deleted"</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669240-e83899e3-283b-45d9-858a-3be8e8178289.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669283-b2829583-f144-4105-92dd-0be20cbbd580.mp4

 </details>

<details>
<summary>Popup appears asking the organizer to confirm if this is the intended action</summary>
 
- PC Chrome

https://user-images.githubusercontent.com/109570108/213669361-539ac267-1033-4f2c-bad6-8ef3a36d4b0f.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669402-f44c8d94-0cc8-4fc0-9ece-1a9661f45e13.mp4

 </details>

<details>
 
<summary> Upon confirmation, user is blocked</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669472-d7f427e6-4c0d-454e-9c42-76fc8efcc2ab.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669541-21662cf0-64e3-46ba-9316-15e05adc9205.mp4

 </details>

<details>

<summary> As the Organizer, Live Chat section can be hidden</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669658-c3dc802d-bc59-4ccd-ab0c-e7d491006ae8.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669727-1d1848c4-ff9d-49cb-a244-e414a84ac1ef.mp4

</details>

<details>
 
<summary>As the Organizer, Live Chat section can be unhidden</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669827-a5beb642-eb6e-4cac-a1bb-ffeaa62efddb.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213669870-1ddaf8ce-af6e-4a42-9d98-b9f85892057a.mp4

</details>

<details>
 
<summary>As the Attendee, Live Chat section can be hidden</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213669958-3c536bd5-ee08-4211-8b18-65514da00d8d.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213670035-a89c22e9-037e-4198-97b3-45bb2187b7a8.mp4

 </details>

<details>
 
<summary>As the Attendee, Live Chat section can be unhidden</summary>

- PC Chrome

https://user-images.githubusercontent.com/109570108/213670135-ea715e52-ed4a-4d34-a35e-e9d1a4a98b2e.mov

-  IOS Safari

https://user-images.githubusercontent.com/109570108/213670234-ebb59987-68bc-494b-975f-373c6555af06.mp4

 </details>

<details>
<summary> "Copy - more than 30 min before the event start time" for EN, JA, ZH</summary>

 - PC Chrome 

![PC Chrome](https://user-images.githubusercontent.com/109570108/213663952-72965e5d-431c-4484-b094-af8cdf7ed98f.png)

![QA_141_B002](https://user-images.githubusercontent.com/109570108/213667361-f6c166ec-f55d-4cbd-bf3e-071da7da4731.png)

![QA_141_B003](https://user-images.githubusercontent.com/109570108/213667580-521beb64-745f-44c5-b3c1-a052b6c2bd77.png)

- IOS Safari

https://user-images.githubusercontent.com/109570108/213666543-e8e96eae-f212-49c9-b09a-87713bc6d676.mov

https://user-images.githubusercontent.com/109570108/213667422-9158f979-c41e-4a5b-99c9-c3d2b0addcc1.mp4

https://user-images.githubusercontent.com/109570108/213667611-b1b34889-2a74-4284-8061-22a9abcbfb75.mp4

</details>

<details>
<summary>"Copy - less than 30 min before the event start time" for EN, JA, ZH</summary>

 - PC Chrome 

![QA_141_B004](https://user-images.githubusercontent.com/109570108/213667691-835be222-f6fc-4c53-81e1-174d06a65975.png)

![QA_141_B005](https://user-images.githubusercontent.com/109570108/213667828-fad39b75-5034-4ef6-8750-92a8078659f1.png)

![QA_141_B006](https://user-images.githubusercontent.com/109570108/213667960-eb6cc50d-8cfb-4bca-bca3-6afc6382bc1a.png)

 - IOS Safari

![QA_141_B004](https://user-images.githubusercontent.com/109570108/213667742-7cb21961-4b3b-4f5d-897a-e8313faa5963.jpeg)

![QA_141_B005](https://user-images.githubusercontent.com/109570108/213667893-1e4b38d9-bf2f-4e67-b630-05d5b382ad61.jpeg)

![QA_141_B006](https://user-images.githubusercontent.com/109570108/213668010-5a8356a6-5134-4e49-8c64-775207f0ba00.jpeg)

</details>

**Comment by monika30peatix** [comment]
Hi Team
While QA-ing QA_150, i found below bugs/weird behavior.
- **Issue1**. On the 'Create a plan' page, user is able to move onto the next page when the 'Plan Name' field data is removed/left blank.
- **Issue2**. When user navigates to the next page, it lands on the bottom of the page and not on the header section of either of the  "Create a plan" or "Subscription form" pages.

(**Note**: I have verified and replicated both the above issues in Restore-test that this behavior is not caused by the change)
